---
site_name: HNOCA
repo_name: devsystemslab/HNOCA-tools
site_dir: docs
docs_dir: site
watch:
  - src/hnoca
repo_url: https://github.com/devsystemslab/HNOCA-tools
repo_name: devsystemslab/HNOCA-tools
theme:
  icon:
    repo: fontawesome/brands/github
  name: 'material'
  logo: assets/images/logo.svg
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: white
    accent: orange
extra_css:
  - stylesheets/extra.css
extra:
  pr_url: https://github.com/devsystemslab/HNOCA-tools/pull/
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home:
    - About: index.md
    - HNOCA-tools: quickstart.md
    - ArchMap: archmap.md
    - Contributing: contributing.md
    - Changelog: CHANGELOG.md
  - Tutorials:
    - Get started: vignettes/get_started.md
    - HNOCA exploration and mapping: vignettes/exploration.ipynb
    - Annotation: vignettes/annotation.ipynb
    - Mapping to the HNOCA: vignettes/atlas_mapping.ipynb
    - Primary reference mapping: vignettes/reference_mapping.ipynb
  - API Reference:
      - mapping:
        - AtlasMapper: api/mapping/AtlasMapper.md
      - snapseed:
        - annotate: api/snapseed/annotate.md
        - annotate_hierarchy: api/snapseed/annotate_hierarchy.md
        - find_markers: api/snapseed/find_markers.md
      - stats:
        - test_de: api/stats/test_de.md
        - test_de_paired: api/stats/test_de_paired.md
        - create_pseudobulk: api/stats/create_pseudobulk.md
      - utils:
        - compute_glycolysis_score: api/utils/compute_glycolysis_score.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            parameter_headings: false
            heading_level: 2
            show_source: false
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - mknotebooks:
      enable_default_jupyter_cell_styling: false
      enable_default_pandas_dataframe_styling: false
  - macros
