name: website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0
      - run: pip install mkdocs-material mknotebooks mkdocstrings
      - run: pip install .
      - run: mkdocs build